# Generated by Django 3.2.4 on 2021-06-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField()),
            ],
        ),
    ]
