# Generated by Django 3.2.4 on 2021-06-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('duration', models.TimeField()),
                ('sets', models.JSONField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
