# Generated by Django 3.2.4 on 2021-07-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.CreateModel(
            name='Exercise_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('sets', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.exercise')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.workout')),
            ],
        ),
    ]
