# Generated by Django 3.2.4 on 2021-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210703_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
