# Generated by Django 3.2.4 on 2021-07-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_details',
            name='sets',
            field=models.JSONField(default='{1:{reps:0, weight:0, distance:0, is_completed:false}, 2:{reps:0, weight:0, distance:0, is_completed:false}}', null=True),
        ),
    ]
