# Generated by Django 3.2.4 on 2021-07-04 23:53

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_exercise_details_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_details',
            name='sets',
            field=models.JSONField(default=diary.models.details_data, null=True),
        ),
    ]
