# Generated by Django 3.2.4 on 2021-07-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_exercise_details_sets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise_Details',
            new_name='WorkoutExerciseDetail',
        ),
    ]
