# Generated by Django 3.2.4 on 2021-07-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_workout_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['date']},
        ),
    ]
